/*
 * File: app/view/OpenFileWindowViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MetaFileData.view.OpenFileWindowViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.openfilewindow',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    stores: {
        ColumnsStore: {
            model: 'MetaFileData.model.ColumnsModel',
            proxy: {
                type: 'ajax',
                url: '/file/upload',
                reader: {
                    type: 'json'
                }
            }
        },
        uploadedFileName: {
            model: 'MetaFileData.model.UploadedFile',
            proxy: {
                type: 'ajax',
                url: '/file/upload',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'metaData'
                },
                {
                    name: 'columns'
                }
            ]
        },
        metaFileStore: {
            model: 'MetaFileData.model.MetaFileModel',
            proxy: {
                type: 'ajax',
                url: '/file/download/metadata'
            },
            fields: [
                {
                    name: 'fileName'
                },
                {
                    name: 'fileSize'
                },
                {
                    name: 'filePath'
                },
                {
                    name: 'fileType'
                },
                {
                    name: 'fileContent'
                },
                {
                    name: 'lastSearch'
                },
                {
                    name: 'lastModefied'
                }
            ]
        },
        ExcelColumnStore: {
            model: 'MetaFileData.model.ExcelColumnModel',
            proxy: {
                type: 'ajax',
                url: '/file/upload/columns',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'excelColumnIndex'
                },
                {
                    name: 'dataType'
                }
            ]
        }
    }

});