/*
 * File: app/view/OpenFileWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MetaFileData.view.OpenFileWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.openfilewindow',

    requires: [
        'MetaFileData.view.OpenFileWindowViewModel',
        'MetaFileData.view.OpenFileWindowViewController',
        'Ext.form.Panel',
        'Ext.form.field.File',
        'Ext.tab.Panel',
        'Ext.form.field.Display',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Action'
    ],

    controller: 'openfilewindow',
    viewModel: {
        type: 'openfilewindow'
    },
    height: 469,
    width: 516,
    title: 'Select File',

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            defaultButton: 'myUploadButton',
            title: '',
            method: 'Post',
            url: '/XtErp/file/upload',
            dockedItems: [
                {
                    xtype: 'filefield',
                    dock: 'top',
                    itemId: 'fileUploadExcelFile',
                    width: 391,
                    fieldLabel: 'Choose the file you want to Open',
                    name: 'uploadedFile'
                }
            ],
            items: [
                {
                    xtype: 'button',
                    itemId: 'myUploadButton',
                    iconCls: 'x-fa fa-upload',
                    text: 'Upload',
                    listeners: {
                        click: 'onButtonClick'
                    }
                }
            ]
        },
        {
            xtype: 'tabpanel',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: 'File Detailes',
                    items: [
                        {
                            xtype: 'displayfield',
                            itemId: 'OpenFileFileName',
                            fieldLabel: 'File Name',
                            value: 'Text ...'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'OpenFileFileType',
                            fieldLabel: 'Type',
                            value: 'Display Field'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'OpenFileFileSize',
                            fieldLabel: 'size',
                            value: 'Display Field'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'OpenFileLastModified',
                            fieldLabel: 'Last Modified',
                            value: 'Display Field',
                            inputType: 'datetime'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'OpenFileLastAccess',
                            fieldLabel: 'Last Access',
                            value: 'Display Field',
                            inputType: 'datetime'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Columns',
                    items: [
                        {
                            xtype: 'gridpanel',
                            title: '',
                            autoLoad: true,
                            bind: {
                                store: '{ExcelColumnStore}'
                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'name',
                                    text: 'Column Name'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    iconCls: 's-fa fa-edit',
                                    items: [
                                        {

                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});